export const apiEndpoints = {
  signUp: "/auth/signup",
  signIn: "/auth/login",
  signOut: "/auth/logout",
  google: "/auth/google",
  me: "/auth/me",
  profile: "/profile",
  checkins: "/checkins",
  planChangeAcceptances: "/billing/plan-change-acceptances",
  billingSubscription: "/billing/subscription",
  stripeCheckoutSession: "/billing/stripe/checkout-session",
  stripePortalSession: "/billing/stripe/portal-session",
  activeWorkout: "/workouts/active",
  workoutSessions: "/workout-sessions",
  activeDiet: "/diets/active",
  dietHistory: "/diets/history",
  foodPreferences: "/preferences/foods",
  gymEquipment: "/preferences/gym-equipment",
  assistantContext: "/assistant/context",
};
