export const apiEndpoints = {
  signUp: "/auth/signup",
  signIn: "/auth/login",
  signOut: "/auth/logout",
  google: "/auth/google",
  me: "/auth/me",
  profile: "/profile",
  settings: "/settings",
  checkins: "/checkins",
  planChangeAcceptances: "/billing/plan-change-acceptances",
  billingSubscription: "/billing/subscription",
  billingTokenHistory: "/billing/token-history",
  stripeCheckoutSession: "/billing/stripe/checkout-session",
  stripeSubscriptionChangeSession: "/billing/stripe/subscription-change-session",
  stripePaymentMethodSession: "/billing/stripe/payment-method-session",
  stripePaymentMethods: "/billing/stripe/payment-methods",
  stripeDefaultPaymentMethod: "/billing/stripe/default-payment-method",
  stripePortalSession: "/billing/stripe/portal-session",
  activeWorkout: "/workouts/active",
  workoutHistory: "/workouts/history",
  workoutSessions: "/workout-sessions",
  activeDiet: "/diets/active",
  dietHistory: "/diets/history",
  dietMealLogs: "/diets/meal-logs",
  foodPreferences: "/preferences/foods",
  gymEquipment: "/preferences/gym-equipment",
  assistantContext: "/assistant/context",
  aiChat: "/ai/chat",
  aiDiet: "/ai/diet",
  aiWorkout: "/ai/workout",
  chatHistory: "/chat/history",
  adminTables: "/admin/tables",
  adminTableData: (name) => `/admin/tables/${name}`,
  adminQuery: "/admin/query",
  adminResetOnboarding: "/admin/reset-onboarding",
};
